---
title: "Données svs participants"
author: "Pierryg"
date: "2025-04-04"
output: html_document
---
```{r}
# Données des participants légers 1
code_sujet_legers_1 <- c("RoD20", "SoR19", "MaN25", "JoR19")
age_sujets_legers_1 <- c(20, 19, 25, 19)
taille_sujets_legers_1 <- c(160, 162, 173, 165)
poids_sujets_legers_1 <- c(53.6, 61.3, 67.8, 70.3)

# Créer le data frame
participants_legers_1 <- data.frame(code_sujet_legers_1, age_sujets_legers_1, taille_sujets_legers_1, poids_sujets_legers_1)



# Données des participants légers 2
code_sujet_legers_2 <- c("LaR18", "ClD21", "GuD19", "AnD22")
age_sujets_legers_2 <- c(18, 21, 19, 22)
taille_sujets_legers_2 <- c(178, 172, 178, 174)
poids_sujets_legers_2 <- c(63, 64, 67, 69)

# Créer le data frame
participants_legers_2 <- data.frame(code_sujet_legers_2, age_sujets_legers_2, taille_sujets_legers_2, poids_sujets_legers_2)


# Données des participants lourds 1
code_sujet_lourds_1 <- c("PaN23", "TaN25", "EnN45", "EnR20")
age_sujets_lourds_1 <- c(23, 25, 45, 20)
taille_sujets_lourds_1 <- c(180, 185, 192, NA)
poids_sujets_lourds_1 <- c(90, 92, 105, 86)

# Créer le data frame
participants_lourds_1 <- data.frame(code_sujet_lourds_1, age_sujets_lourds_1, taille_sujets_lourds_1, poids_sujets_lourds_1)


# Données des participants lourds 2
code_sujet_lourds_2 <- c("EnN45", "ReD28", "MaN23", "PiN19")
age_sujets_lourds_2 <- c(45, 28, 25, 19)
taille_sujets_lourds_2 <- c(192, 193, 186, 193)
poids_sujets_lourds_2 <- c(105, 93, 89, 89)

# Créer le data frame
participants_lourds_2 <- data.frame(code_sujet_lourds_2, age_sujets_lourds_2, taille_sujets_lourds_2, poids_sujets_lourds_2)


```

```{r}
#Visualisation et calculs 
#Moyennes des catégories

sapply(participants_legers_1[, c("age_sujets_legers_1", "poids_sujets_legers_1", "taille_sujets_legers_1")], mean)

sapply(participants_legers_2[, c("age_sujets_legers_2", "poids_sujets_legers_2", "taille_sujets_legers_2")], mean)

sapply(participants_lourds_1[, c("age_sujets_lourds_1", "poids_sujets_lourds_1", "taille_sujets_lourds_1")], mean)

sapply(participants_lourds_2[, c("age_sujets_lourds_2", "poids_sujets_lourds_2", "taille_sujets_lourds_2")], mean)

#écart-type des catégories

sapply(participants_legers_1[, c("age_sujets_legers_1", "poids_sujets_legers_1", "taille_sujets_legers_1")], sd)

sapply(participants_legers_2[, c("age_sujets_legers_2", "poids_sujets_legers_2", "taille_sujets_legers_2")], sd)

sapply(participants_lourds_1[, c("age_sujets_lourds_1", "poids_sujets_lourds_1", "taille_sujets_lourds_1")], sd)

sapply(participants_lourds_2[, c("age_sujets_lourds_2", "poids_sujets_lourds_2", "taille_sujets_lourds_2")], sd)

#Médiane des catégories

sapply(participants_legers_1[, c("age_sujets_legers_1", "poids_sujets_legers_1", "taille_sujets_legers_1")], median)

sapply(participants_legers_2[, c("age_sujets_legers_2", "poids_sujets_legers_2", "taille_sujets_legers_2")], median)

sapply(participants_lourds_1[, c("age_sujets_lourds_1", "poids_sujets_lourds_1", "taille_sujets_lourds_1")], median)

sapply(participants_lourds_2[, c("age_sujets_lourds_2", "poids_sujets_lourds_2", "taille_sujets_lourds_2")], median)


```

